language: android

android:
  components:
    - tools
    - tools # Duplicated as per https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943
    - build-tools-25.0.2
    - android-25
    - platform-tools
    - extra-android-m2repository

jdk:
  - oraclejdk8

env:
  global:
    - TOOLS=${ANDROID_HOME}/tools
    - PATH=${ANDROID_HOME}:${ANDROID_HOME}/emulator:${TOOLS}:${TOOLS}/bin:${ANDROID_HOME}/platform-tools:${PATH}

install:
  - echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout;1.0.2"
  - echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout-solver;1.0.2"

script:
  - ./gradlew :app-generated-injector:assembleDebug
  - ./gradlew :app:assembleDebug
